/**
 * Records Base Types
 *
 * Core record types and enums for the medical records system.
 */

export type SpecialtyType = 'medicina' | 'nutricao' | 'psicologia';

export enum RecordType {
  NOTE = 'note',
  SOAP = 'soap',
  PRESCRIPTION = 'prescription',
  EXAM_REQUEST = 'exam_request',
  ANTHROPOMETRY = 'anthropometry',
  DIET_PLAN = 'diet_plan',
  PSYCHO_SESSION = 'psycho_session'
}

/**
 * Attachment metadata for record files.
 */
export interface RecordAttachment {
  id: string;
  name: string;
  url: string;
  type: 'pdf' | 'image';
  size: number; // bytes
  uploadedAt: string;
  uploadedBy: string;
}

/**
 * Base interface for all records (Polymorphic)
 */
export interface BaseRecord {
  id: string;
  patientId: string;
  date: string;
  professional: string;
  type: RecordType;
  specialty: SpecialtyType;
  // Versioning fields (optional for backwards compatibility with existing records)
  version?: number;
  updatedAt?: string;
  updatedBy?: string;
  // Attachments
  attachments?: RecordAttachment[];
}

/**
 * Fields that are auto-generated by the service and should not be provided on create.
 */
export type RecordAutoFields = 'id' | 'date' | 'professional' | 'version' | 'updatedAt' | 'updatedBy' | 'attachments';
